cpims/cpims/urls.py
"""
cpims URL Configuration.

Other urls are import
Put here only urls not specific to app
"""
from django.conf.urls import include, url
from django.contrib import admin
from cpovc_auth import urls as auth_urls
from cpovc_registry import urls as registry_urls
from cpovc_forms import urls as forms_urls
from cpovc_reports import urls as reports_urls
from cpovc_gis import urls as gis_urls
from cpovc_api import urls as api_urls
from cpovc_ovc import urls as ovc_urls
from cpovc_settings import urls as settings_urls
from cpovc_manage import urls as manage_urls
from cpovc_help import urls as help_urls
from notifications import urls as noti_urls
from django.contrib.auth.views import (
    password_reset_done, password_change, password_change_done)
from cpovc_auth.views import password_reset
from django.views.generic import TemplateView
from cpovc_dashboard import urls as dashboard_api_urls
from cpovc_access.forms import StrictPasswordChangeForm


urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
    # url(r'^$', 'cpovc_auth.views.log_in', name='home'),
    url(r'^$', 'cpims.views.home', name='home'),
    url(r'^accounts/request/$', 'cpims.views.access', name='access'),
    url(r'^accounts/terms/(?P<id>\d+)/$', 'cpovc_access.views.terms',
        name='terms'),
    url(r'^login/$', 'cpovc_auth.views.log_in', name='login'),
    url(r'^logout/$', 'cpovc_auth.views.log_out', name='logout'),
    url(r'^register/$', 'cpovc_auth.views.register', name='register'),
    url(r'^auth/', include(auth_urls)),
    url(r'^registry/', include(registry_urls)),
    url(r'^forms/', include(forms_urls)),
    url(r'^reports/', include(reports_urls)),
    url(r'^gis/', include(gis_urls)),
    url(r'^api/v1/', include(api_urls)),
    url(r'^ovcare/', include(ovc_urls)),
    url(r'^settings/', include(settings_urls)),
    url(r'^manage/', include(manage_urls)),
    url(r'^help/', include(help_urls)),
    url(r'^notifications/', include(noti_urls, namespace='notifications')),
    url(r'^dashboard/(?P<did>[A-Z{2}\Z]+)/$',
        'cpovc_registry.views.dashboard', name='dashboard'),
    url(r'^accounts/login/$', 'cpovc_auth.views.log_in', name='login'),
    url(r'^accounts/password/reset/$', password_reset,
        {'template_name': 'registration/password_reset.html'},
        name='password_reset'),
    url(r'^accounts/password/reset/done/$', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^accounts/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'cpovc_auth.views.reset_confirm', name='password_reset_confirm'),
    url(r'^reset/$', 'cpovc_auth.views.reset', name='reset'),
    url(r'^accounts/password/change/$', password_change,
        {'post_change_redirect': '/accounts/password/change/done/',
         'template_name': 'registration/password_change.html',
         'password_change_form': StrictPasswordChangeForm},
        name='password_change'),
    url(r'^accounts/password/change/done/$', password_change_done,
        {'template_name': 'registration/password_change_done.html'}),
    url(r'^F57665A859FE7CFCDB6C8935196374AD\.txt$',
        TemplateView.as_view(template_name='comodo.txt',
                             content_type='text/plain')),
    url(r'^d/$', 'cpovc_dashboard.views.ovc_dashboard', name='ovc_dashboard'),
    url(r'^d/hivstat/', 'cpovc_dashboard.views.ovc_dashboard_hivstat', name='hivstat_dash'),
    url(r'^d/services/', 'cpovc_dashboard.views.ovc_dashboard_services', name='services_dash'),
    url(r'^d/cm/', 'cpovc_dashboard.views.ovc_dashboard_cm', name='cm_dash'),
    url(r'^api/v2/', include(dashboard_api_urls)),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                               content_type='text/plain'))]

handler400 = 'cpims.views.handler_400'
handler404 = 'cpims.views.handler_404'
handler500 = 'cpims.views.handler_500'

admin.site.site_header = 'CPIMS Administration'
admin.site.site_title = 'CPIMS administration'
admin.site.index_title = 'CPIMS admin'

cpims/cpovc_api/urls.py
"""API urls."""
from django.conf.urls import url, include
from rest_framework import routers
from .views import (
    SettingsViewSet, GeoViewSet, BasicCRSView, CountryViewSet,
    basic_crs, OrgUnitViewSet)

router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
router.register(r'country', CountryViewSet, base_name='Country')
# Wire up our API using automatic URL routing.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^settings/$', SettingsViewSet.as_view()),
    url(r'^geo/$', GeoViewSet.as_view()),
    url(r'^ou/$', OrgUnitViewSet.as_view()),
    url(r'^crs-old/$', BasicCRSView.as_view()),
    url(r'^crs/$', basic_crs),
]

cpims/urls.py
"""
cpims URL Configuration.

Other urls are import
Put here only urls not specific to app
"""
from importlib.resources import path
from django.conf.urls import include, url
from django.contrib import admin
from cpovc_auth import urls as auth_urls
from cpovc_registry import urls as registry_urls
from cpovc_forms import urls as forms_urls
from cpovc_reports import urls as reports_urls
from cpovc_gis import urls as gis_urls
from cpovc_api import urls as api_urls
from cpovc_ovc import urls as ovc_urls
from cpovc_settings import urls as settings_urls
from cpovc_manage import urls as manage_urls
from cpovc_help import urls as help_urls
from notifications import urls as noti_urls
from django.contrib.auth.views import (
    password_reset_done, password_change, password_change_done)
from cpovc_auth.views import password_reset
from django.views.generic import TemplateView
from cpovc_dashboard import urls as dashboard_api_urls
from cpovc_access.forms import StrictPasswordChangeForm


urlpatterns = [

    path('admin/', include(admin.site.urls), name='admin'),
    #path('/', 'cpovc_auth.views.log_in', name='home'),
    path('/', 'cpims.views.home', name='home'),
    path('accounts/request/', 'cpims.views.access', name='access'),
    path('accounts/terms/(?P<id>\d+)/', 'cpovc_access.views.terms',
        name='terms'),
    path('login/', 'cpovc_auth.views.log_in', name='login'),
    path('logout/', 'cpovc_auth.views.log_out', name='logout'),
    path('register/', 'cpovc_auth.views.register', name='register'),
    path('auth/', include(auth_urls)),
    path('registry/', include(registry_urls)),
    path('forms/', include(forms_urls)),
    path('reports/', include(reports_urls)),
    path('gis/', include(gis_urls)),
    path('api/v1/', include(api_urls)),
    path('ovcare/', include(ovc_urls)),
    path('settings/', include(settings_urls)),
    path('manage/', include(manage_urls)),
    path('help/', include(help_urls)),
    path('notifications/', include(noti_urls, namespace='notifications')),
    path('dashboard/(?P<did>[A-Z{2}\Z]+)/$',
        'cpovc_registry.views.dashboard', name='dashboard'),
    path('accounts/login/$', 'cpovc_auth.views.log_in', name='login'),
    path('accounts/password/reset/$', password_reset,
        {'template_name': 'registration/password_reset.html'},
        name='password_reset'),
    path('accounts/password/reset/done/$', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    path('accounts/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'cpovc_auth.views.reset_confirm', name='password_reset_confirm'),
    path('reset/', 'cpovc_auth.views.reset', name='reset'),
    path('accounts/password/change/$', password_change,
        {'post_change_redirect': '/accounts/password/change/done/',
         'template_name': 'registration/password_change.html',
         'password_change_form': StrictPasswordChangeForm},
        name='password_change'),
    path('accounts/password/change/done/', password_change_done,
        {'template_name': 'registration/password_change_done.html'}),
    path('F57665A859FE7CFCDB6C8935196374AD\.txt$',
        TemplateView.as_view(template_name='comodo.txt',
                             content_type='text/plain')),
    path('d/', 'cpovc_dashboard.views.ovc_dashboard', name='ovc_dashboard'),
    path('d/hivstat/', 'cpovc_dashboard.views.ovc_dashboard_hivstat', name='hivstat_dash'),
    path('d/services/', 'cpovc_dashboard.views.ovc_dashboard_services', name='services_dash'),
    path('d/cm/', 'cpovc_dashboard.views.ovc_dashboard_cm', name='cm_dash'),
    path('api/v2/', include(dashboard_api_urls)),
    path('robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                               content_type='text/plain'))]

handler400 = 'cpims.views.handler_400'
handler404 = 'cpims.views.handler_404'
handler500 = 'cpims.views.handler_500'

admin.site.site_header = 'CPIMS Administration'
admin.site.site_title = 'CPIMS administration'
admin.site.index_title = 'CPIMS admin'

update_env/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cpims/cpovc_api/models.py
from django.db import models

# Create your models here.

cpims/cpovc_dashboard/models.py
from django.db import models

# Create your models here.

cpims/cpovc_gis copy/models.py
from django.db import models

# Create your models here.

cpims/cpovc_gis/models.py
from django.db import models

# Create your models here.

cpims/cpovc_help/models.py
import os
from django.db import models
from cpovc_registry.models import RegPerson


class OVCDownloads(models.Model):
    doc_type = models.IntegerField()
    name = models.CharField(max_length=255)
    version = models.DecimalField(max_digits=5, decimal_places=2)
    doc_date = models.DateField()
    doc_details = models.TextField()
    downloads = models.BigIntegerField(default=0)
    doc_tags = models.CharField(max_length=255)
    document = models.FileField(upload_to='documents')
    person = models.ForeignKey(RegPerson, null=True)
    is_public = models.BooleanField(default=False)
    is_void = models.BooleanField(default=False)

    def _filename(self):
        return os.path.basename(self.document.name)

    def _filesize(self):
        return self.document.size

    filename = property(_filename)
    filesize = property(_filesize)

    class Meta:
        """Override table details."""

        db_table = 'ovc_downloads'
        verbose_name = 'DCS / OVC Document'
        verbose_name_plural = 'DCS / OVC Documents'

    def __unicode__(self):
        """To be returned by admin actions."""
        return self.name


class OVCFAQ(models.Model):
    faq_order = models.IntegerField(default=1)
    faq_title = models.CharField(max_length=255)
    faq_details = models.TextField()
    faq_timestamp = models.DateTimeField()
    is_void = models.BooleanField(default=False)

    class Meta:
        """Override table details."""

        db_table = 'ovc_faq'
        verbose_name = 'FAQ Detail'
        verbose_name_plural = 'FAQ Details'

    def __unicode__(self):
        """To be returned by admin actions."""
        return self.faq_title

cpims/cpovc_reports/models.py
# import uuid
from django.db import models
from django.utils import timezone
from cpovc_registry.models import RegOrgUnit, RegPersonsTypes, RegPerson
from cpovc_forms.models import OVCCaseRecord, OVCPlacement


class RPTCaseLoad(models.Model):
    """Model for Case Load Report."""

    case = models.ForeignKey(OVCCaseRecord)
    case_serial = models.CharField(max_length=40, null=False)
    case_reporter_id = models.CharField(max_length=4)
    case_reporter = models.CharField(max_length=250)
    case_perpetrator_id = models.CharField(max_length=4, null=True)
    case_perpetrator = models.CharField(max_length=250, null=True)
    case_category_id = models.CharField(max_length=4)
    case_category = models.CharField(max_length=250)
    date_of_event = models.DateField(default=timezone.now)
    place_of_event_id = models.CharField(max_length=4)
    place_of_event = models.CharField(max_length=250)
    sex_id = models.CharField(max_length=4)
    sex = models.CharField(max_length=10)
    dob = models.DateField(default=timezone.now, null=True)
    county_id = models.IntegerField(default=0)
    county = models.CharField(max_length=250, null=True)
    sub_county_id = models.IntegerField(default=0)
    sub_county = models.CharField(max_length=250, null=True)
    org_unit = models.ForeignKey(RegOrgUnit)
    org_unit_name = models.CharField(max_length=250, null=True)
    case_status = models.IntegerField(null=False)
    intervention_id = models.CharField(max_length=4, null=True)
    intervention = models.CharField(max_length=250, null=True)
    case_year = models.IntegerField(default=0)
    case_month = models.IntegerField(default=0)
    case_quota = models.IntegerField(default=0)
    case_count = models.IntegerField(default=1)
    age_range = models.CharField(max_length=20, null=True, blank=True)
    knbs_age_range = models.CharField(max_length=20, null=True, blank=True)
    age = models.IntegerField(default=0, null=True)
    case_date = models.DateField(null=True, default=timezone.now)
    system_date = models.DateField(null=True, default=timezone.now)
    is_void = models.BooleanField(default=False)

    class Meta:
        """Override table details."""

        db_table = 'rpt_case_load'
        verbose_name = 'Protection Case data'
        verbose_name_plural = 'Protection Cases data'

    def __unicode__(self):
        """To be returned by admin actions."""
        return self.case_serial


class SIPopulation(OVCPlacement):
    class Meta:
        proxy = True
        verbose_name = 'SI Population'
        verbose_name_plural = 'SI Populations'


class CCIPopulation(OVCPlacement):
    class Meta:
        proxy = True
        verbose_name = 'CCI Population'
        verbose_name_plural = 'CCI Populations'


class SystemUsage(RegPersonsTypes):
    class Meta:
        proxy = True
        verbose_name = 'System Usage'
        verbose_name_plural = 'System Usages'


class RPTIPopulation(models.Model):
    """Model for Institution Population."""

    case = models.ForeignKey(OVCCaseRecord)
    case_serial = models.CharField(max_length=40, null=False)
    person = models.ForeignKey(RegPerson)
    admission_number = models.CharField(max_length=40, null=False)
    org_unit = models.ForeignKey(RegOrgUnit)
    org_unit_name = models.CharField(max_length=250, null=True)
    org_unit_type_id = models.CharField(max_length=4, null=True)
    org_unit_type = models.CharField(max_length=250, null=True)
    sex_id = models.CharField(max_length=4)
    sex = models.CharField(max_length=10)
    dob = models.DateField(default=timezone.now, null=True)
    age = models.IntegerField(default=0, null=True)
    age_now = models.IntegerField(default=0, null=True)
    age_range = models.CharField(max_length=20, null=True, blank=True)
    knbs_age_range = models.CharField(max_length=20, null=True, blank=True)
    admission_date = models.DateField(default=timezone.now)
    admission_type_id = models.CharField(max_length=4)
    admission_type = models.CharField(max_length=250)
    admission_reason_id = models.CharField(max_length=4)
    admission_reason = models.CharField(max_length=250)
    case_status_id = models.IntegerField(null=False, default=1)
    case_status = models.CharField(max_length=20, null=False)
    case_category_id = models.CharField(max_length=4)
    case_category = models.CharField(max_length=250)
    sub_category_id = models.CharField(max_length=4)
    sub_category = models.CharField(max_length=250)
    discharge_date = models.DateField(null=True, default=timezone.now)
    discharge_type_id = models.CharField(max_length=4, null=True)
    discharge_type = models.CharField(max_length=250, null=True)
    county_id = models.IntegerField(default=0)
    county = models.CharField(max_length=250, null=True)
    sub_county_id = models.IntegerField(default=0)
    sub_county = models.CharField(max_length=250, null=True)
    system_date = models.DateField(null=True, default=timezone.now)
    system_timestamp = models.DateTimeField(null=True, default=timezone.now)
    is_void = models.BooleanField(default=False)

    class Meta:
        """Override table details."""

        db_table = 'rpt_inst_population'
        verbose_name = 'Population Report'
        verbose_name_plural = 'Population Reports'

    def __unicode__(self):
        """To be returned by admin actions."""
        return self.case_serial

cpims/cpovc_settings/models.py
import uuid
from django.db import models
from cpovc_forms.models import OVCCaseRecord
from cpovc_registry.models import RegPerson, RegOrgUnit
from django.utils import timezone
from cpovc_auth.models import AppUser


class CaseDuplicates(models.Model):
    """Model for managing duplicate cases."""

    duplicate_id = models.UUIDField(default=uuid.uuid4, editable=False)
    case_category_id = models.CharField(max_length=4)
    person = models.ForeignKey(RegPerson)
    organization_unit = models.ForeignKey(RegOrgUnit)
    case = models.ForeignKey(OVCCaseRecord)
    created_by = models.ForeignKey(AppUser, null=True, related_name='creator')
    created_at = models.DateTimeField(default=timezone.now)
    updated_by = models.ForeignKey(AppUser, null=True, related_name='updator')
    updated_at = models.DateTimeField(null=True)
    action_id = models.IntegerField(default=1)
    interventions = models.IntegerField(default=0)
    is_void = models.BooleanField(default=False)

    class Meta:
        """Override table details."""

        db_table = 'case_duplicates'
        verbose_name = 'Duplicated case'
        verbose_name_plural = 'Duplicated Cases'

cpims/templates/registry/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block page_title %} Dashboard {% endblock %}

{% load crispy_forms_tags %}

{% block style_code %}
<link href="{% static 'plugins/parsley/src/parsley.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/bootstrap-datepicker/css/datepicker3.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/bootstrap-multiselect/dist/css/bootstrap-multiselect.css' %}" rel="stylesheet">

{% endblock %}

{% block primary %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
	<li><a href="#">Home</a></li>
	<li class="active">Registry</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Registry <small>Update Organisational Unit</small></h1>
<!-- end page-header -->
<div id="messages" class="alert alert-danger fade in" style="display: none;" tabindex="1">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <p class="invalid-form-message"></p>
</div>
<!-- begin row -->
<div class="row">
    <!-- Start content area -->
    	<!-- begin row -->
		<div class="row">
            <!-- begin col-6 -->
		    <div class="col-12">
		        <!-- begin panel -->
		        <form class="form-horizontal form-bordered" data-parsley-validate="true" name="demo-form" id="edit_org_unit" method="post">
		        {% csrf_token %}
		        <input type='radio' class="edit_org" name='edit_org' value="1" checked="checked"> Update Organization Unit registration details
		        <div class="separator"></div>
		        <div id="edit_part">
                <div class="panel panel-inverse" data-sortable-id="form-validation-1">
                    <div class="panel-heading">
                        <div class="panel-heading-btn">
                            <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                            <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        </div>
                        <h4 class="panel-title">About the Organisation</h4>
                    </div>
                    <div class="panel-body panel-form">
						<div class="form-group">
							<label class="control-label col-md-4 col-sm-4" for="org_unit_name">Name of Organisation Unit * :</label>
							<div class="col-md-6 col-sm-6">
									{{ form.org_unit_name }}
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-4 col-sm-4" for="date_reg">Date when the organisation Unit was set up or became operational * :</label>
							<div class="col-md-6 col-sm-6">
                                {{ form.reg_date }}
							</div>
						</div>
                    </div>
                </div>
                <!-- end panel -->
                <!-- begin panel -->
                <div class="panel panel-inverse" data-sortable-id="form-validation-1">
                    <div class="panel-heading">
                        <div class="panel-heading-btn">
                            <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                            <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        </div>
                        <h4 class="panel-title">Organisation Type</h4>
                    </div>
                    <div class="panel-body panel-form">
						<div class="form-group">
							<label class="control-label col-md-4 col-sm-4" for="org_unit_type">Type of organisation Unit :</label>
							<div class="col-md-6 col-sm-6">
								{{ form.org_unit_type }}
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-4 col-sm-4" for="legal_reg_type">Legal Registration type :</label>
							<div class="col-md-6 col-sm-6">
								{{ form.org_reg_type }}
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-4 col-sm-4" for="legal_reg_number">Legal Registration Number :</label>
							<div class="col-md-6 col-sm-6">
								{{ form.legal_reg_number }}
							</div>
						</div>
                        <div class="form-group">
							<label class="control-label col-md-4 col-sm-4" for="parent_unit">Parent Unit :</label>
							<div class="col-md-6 col-sm-6">
								{{ form.parent_org_unit }}
							</div>
						</div>
                    </div>
                </div>
                <!-- end panel -->
                <!-- begin panel -->
                <div class="panel panel-inverse" data-sortable-id="form-validation-1">
                    <div class="panel-heading">
                        <div class="panel-heading-btn">
                            <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                            <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        </div>
                        <h4 class="panel-title">Where located / Providing services</h4>
                    </div>
                    <div class="panel-body panel-form">
						<div class="form-group">
							<label class="control-label col-md-4 col-sm-4" for="sub_county">Sub County :</label>
							<div class="col-md-6 col-sm-6">
								{{ form.sub_county }}
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-4 col-sm-4" for="wards">Wards :</label>
							<div class="col-md-6 col-sm-6">
								{{ form.ward }}
							</div>
						</div>
                    </div>
                </div>
                <!-- end panel -->
                <!-- begin panel -->
                <div class="panel panel-inverse" data-sortable-id="form-validation-1">
                    <div class="panel-heading">
                        <div class="panel-heading-btn">
                            <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                            <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        </div>
                        <h4 class="panel-title">Organisation Unit contact details</h4>
                    </div>
	                <div class="panel-body panel-form">
	                    {% crispy cform %}
	                </div>
	            </div>
	            </div><!-- end view part -->
	            <!-- end panel -->
	            <input type='radio' class="edit_org" name='edit_org' value="2"> Organization Unit closed / No longer functional.
	            <!-- begin panel -->
                <div class="panel panel-inverse" data-sortable-id="form-validation-1">
                    <div class="panel-body panel-form">
						<div class="form-group">
							<label class="control-label col-md-4 col-sm-4" for="parent_unit">Date closed :</label>
							<div class="col-md-6 col-sm-6">
								{{ form.close_date }}
							</div>
						</div>
                    </div>
                </div>
                <!-- end panel -->
	            <input type='radio' class="edit_org" name='edit_org' value="3"> Organization Unit never existed. (Registration mistake or duplicate.)
                <!-- begin panel -->
                <div class="panel panel-inverse" data-sortable-id="form-validation-1">
                    <div class="panel-body panel-form">
						<div class="form-group">
							<label class="control-label col-md-4 col-sm-4"></label>
							<div class="col-md-6 col-sm-6">
							    <p></p>
								<button type="submit" class="btn btn-primary">Submit</button>
								<button type="submit" class="btn btn-default">Cancel</button>
								<p></p>
							</div>
						</div>
                    </div>
                </div>
                </form>
            </div>
            <!-- end col-6 -->
        </div>
    
	<!-- End content area -->
</div>
<!-- end row -->
{% endblock %}

{% block lazy_javascript_code %}
	<script src="{% static 'js/apps.js' %}"></script>
	<script src="{% static 'plugins/parsley/dist/parsley.js' %}"></script>
	<script src="{% static 'plugins/bootstrap-multiselect/dist/js/bootstrap-multiselect.js' %}"></script>
	<script type="text/javascript">
		window.Parsley
		  .addValidator('isngo', {
		    requirementType: 'string',
		    validateString: function(value, requirement) {
		      var refs = $(requirement).val();
		      var reff = $(requirement);
		      var vals = ["TNND", "TNNM", "TNNH"];
		      if (reff.length){
                if($.inArray(refs, vals) > -1){
                	if (value != '') return true; else return false;
                }else{
                	return true;
                }
		      }else{
		      	return false;
		      }
		    },
		    messages: {
		      en: 'Registration details should be provided for this unit.'
		    }
		  });
		window.Parsley
		    .addValidator('ishq', {
		    requirementType: 'string',
		    validateString: function(value, requirement) {
		      var refs = $(requirement).val();
		      var reff = $(requirement);
		      if (reff.length){
                if(refs != 'TNGN'){
                	if (value != '') return true; else return false;
                }else{
                	return true;
                }
		      }else{
		      	return false;
		      }
		    },
		    messages: {
		      en: 'Parent organization unit must be provided.'
		    }
		  });
		</script>
	<script>
		jQuery(document).ready(function() {
			$('html,body').scrollTop(0);
			App.init();
			$('#id_sub_county').multiselect({
				enableFiltering: true,
				filterBehavior: 'both',
				numberDisplayed: 0,
				maxHeight: 200,
				enableCaseInsensitiveFiltering: true
			});
			$('#id_ward').multiselect({
				enableFiltering: true,
				filterBehavior: 'both',
				numberDisplayed: 0,
				maxHeight: 200,
				enableCaseInsensitiveFiltering: true
			});
			$(".edit_org").click(function(e) {
				var res = $('input[name=edit_org]:checked', '#edit_org_unit').val();
				if (res == '2'){
			       $("#edit_part").hide();
			       $("#editdate").prop("readonly", false);
			    }else if (res == '1'){
			       $("#edit_part").show();
			       $("#editdate").prop("readonly", true);
			    }else if (res == '3'){
			       $("#edit_part").hide();
			       $("#editdate").prop("readonly", true);
			   }
		    });
		});
	</script>

    <script type="text/javascript">
		$(function () {
		  $('#edit_org_unit').parsley().on('form:validate', function (formInstance) {
		    var ok = formInstance.isValid('primary', true);
		    $(".alert").show();
		    $('.invalid-form-message')
		      .html(ok ? '' : 'You must correctly fill the mandatory fields.')
		      .toggleClass('filled', !ok);
		    if (!ok){
		      formInstance.validationResult = false;
		    }else{
		    	$(".alert").hide();
		    }
		  });
		});
	</script>
{% endblock %}